---

- name: Install echotest
  kubernetes.core.k8s:
    context: "{{ k8s_context }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: "{{ k8s_echotest_state }}"
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
    definition: "{{ lookup('template', 'echotest.yml') }}"
