# Reference for values accepted by the ingress-nginx chart:
# https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
controller:
  replicaCount: {{ k8s_ingress_nginx_replica_count }}