##jinja2: lstrip_blocks: "True"
# On AWS, creating this ConfigMap grants access to IAM users.
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    {% for user in k8s_iam_users -%}
    - groups:
      - system:masters
      userarn: arn:aws:iam::{{ aws_account_id }}:user/{{ user }}
      username: arn:aws:iam::{{ aws_account_id }}:user/{{ user }}
    {% endfor %}
  mapRoles: |
    {% for role in k8s_iam_roles -%}
    - rolearn: {{ role }}
      username: system:node:{% raw %}{{EC2PrivateDNSName}}{% endraw %}
      groups:
      - system:masters
    {% endfor -%}
